import {
  DashbboardMobileHeader,
  Dashboard,
  DashboardMain,
  DashboardMobile,
  DashboardSidebar,
  DashboardSidebarHeader,
  Flex,
} from "@playbook/ui";
import { MessagesSquare } from "lucide-react";
import type { Metadata } from "next";
import { CreateMessageForm } from "../_forms/create-message";
import {
  MobileNavigation,
  SidebarNavigation,
} from "./_components/dashboard-navigation";
import { UserDropdown } from "./_components/user-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Logo = () => (
  <Flex gap={"xs"} align={"center"}>
    <MessagesSquare className="h-5 w-5" />
    <span className="font-medium text-lg">Logo</span>
  </Flex>
);

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Dashboard>
      {/* // Mobile top navbar */}
      <DashboardMobile>
        <DashbboardMobileHeader>
          <Logo />
          <UserDropdown />
        </DashbboardMobileHeader>
        <MobileNavigation />
      </DashboardMobile>
      {/* // Desktop sidebar */}
      <DashboardSidebar>
        <DashboardSidebarHeader>
          <Logo />
          <UserDropdown />
        </DashboardSidebarHeader>
        <Flex align={"center"} justify={"between"} className="px-4">
          <CreateMessageForm />
        </Flex>
        <SidebarNavigation />
      </DashboardSidebar>
      {/* //Main */}
      <DashboardMain>{children}</DashboardMain>
    </Dashboard>
  );
}
